### ISSUE TITLE
Cannot load scenes, stuck at loading ~70%

### ISSUE THREAD

**Issue by GrieverShockwavePulsar** [Zakarik/token-action-hud-mm3#2]
Having several issues trying to run **v1.16.0** on my Forge server, for some reason it won't complete loading and I can't tell what the problem is.  The closest I can find is from the logger when the server locks:

Loaded icons/svg/light.svg (2%) foundry.js:29223:13
Loaded icons/svg/eye.svg (5%) foundry.js:29223:13
Loaded icons/svg/explosion.svg (7%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/sun.svg (9%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/net.svg (11%) foundry.js:29223:13
Loaded icons/svg/cowled.svg (14%) foundry.js:29223:13
Loaded icons/svg/combat.svg (16%) foundry.js:29223:13
Loaded icons/svg/door-open-outline.svg (18%) foundry.js:29223:13
Loaded icons/svg/up.svg (20%) foundry.js:29223:13
Loaded icons/svg/down.svg (23%) foundry.js:29223:13
Loaded icons/svg/aura.svg (25%) foundry.js:29223:13
Loaded icons/svg/skull.svg (27%) foundry.js:29223:13
Loaded icons/svg/daze.svg (30%) foundry.js:29223:13
Loaded icons/svg/light-off.svg (32%) foundry.js:29223:13
Loaded icons/svg/blind.svg (34%) foundry.js:29223:13
Loaded icons/svg/padlock.svg (36%) foundry.js:29223:13
Loaded icons/svg/sound-off.svg (39%) foundry.js:29223:13
Loaded icons/svg/sound.svg (41%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/invisible.svg (43%) foundry.js:29223:13
Loaded icons/svg/deaf.svg (45%) foundry.js:29223:13
Loaded icons/svg/degen.svg (48%) foundry.js:29223:13
Loaded icons/svg/wall-direction.svg (50%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/door-secret-outline.svg (52%) foundry.js:29223:13
Loaded icons/svg/paralysis.svg (55%) foundry.js:29223:13
Loaded icons/svg/falling.svg (57%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/downgrade.svg (59%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/unconscious.svg (61%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/sleep.svg (64%) foundry.js:29223:13
Loaded icons/svg/door-closed-outline.svg (66%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
Loaded icons/svg/door-locked-outline.svg (68%) foundry.js:29223:13
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126

I do not know if these are related.

**Comment by GrieverShockwavePulsar** [comment]
Wanted to add I'm using V11 (build 305) as the Foundry version.

**Comment by Zakarik** [comment]
You use Firefox ? Version ?

**Comment by GrieverShockwavePulsar** [comment]
Yes, using Firefox v115.0.2

**Comment by GrieverShockwavePulsar** [comment]
As a test I did try and run it on Chrome with no issues

**Comment by Zakarik** [comment]
Should be corrected in the update of the system just released.

**Comment by GrieverShockwavePulsar** [comment]
Confirmed working in Firefox.
