### ISSUE TITLE
BUG: Token action HUD for M&M not working after last update

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/token-action-hud-mm3#5]
![image](https://github.com/Zakarik/token-action-hud-mm3/assets/138895824/43c322a5-5f3a-437b-8aa0-61e19593938a)

When loading with the new Token Action HUD core, the game gives a UI notifications of "The installed Token Action HUD system module reuires Token Action HUD Core Module version 1.4. Install the required version to continue using Token Action HUD." and no token action HUD is working.

larkinabout said to "Roll back to Token Action HUD Core 1.4.22 until the Token Action HUD module for the system supports 1.5"

**Comment by Zakarik** [comment]
This should be fixed.
I haven't tested it in depth, so if there's a bug following the update, don't hesitate to let me know!
